"""empty message

Revision ID: bc93469102aa
Revises: 59aff3c55972
Create Date: 2022-06-01 18:44:33.240766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc93469102aa'
down_revision = '59aff3c55972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('pf', sa.String(), server_default='1/1/1/1/1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('images')
    op.drop_constraint(None, 'player_history', type_='foreignkey')
    op.drop_column('player_history', 'img_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_history', sa.Column('img_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'player_history', 'images', ['img_id'], ['id'])
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('answer', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.VARCHAR(), nullable=False),
    sa.Column('pf', sa.VARCHAR(), server_default=sa.text("'1/1/1/1/1'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('Images')
    # ### end Alembic commands ###
